name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install black flake8 bandit pytest pytest-cov

      - name: Format check (Black)
        run: black --check .

      - name: Lint (Flake8)
        run: flake8 . --max-line-length=100

      - name: Tests (Pytest)
        run: pytest --cov=app

      - name: Security scan (Bandit)
        run: bandit -r app -ll -ii
